{{- if eq .Release.namespace "kubernetes-dashboard" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-read-only-sa
{{- end }}
