apiVersion: v1
kind: Secret
metadata:
  name: local-selfsigned-tls
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: kubernetes.io/tls
data:
  {{- (.Files.Glob "certs/*").AsSecrets | nindent 2 }}
